In [8]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

In [20]:
data ={'Fahrzeug': ['auto', 'auto', 'Motorrad', 'auto', 'Motorrad', 'auto', 'Motorrad', 'auto', 'Motorrad', 'auto'],
       'PS': [150, 200, 250, 180, 160, 220, 210, 190, 230, 170],
       'Preis': [35000, 35000, 40000, 25000, 22000, 32000, 28000, 27000, 32000, 25000],
       'Reichweite': [500, 600, 550, 700, 650, 750, 800, 720, 680, 640]}
DF_obj = pd.DataFrame(data)
DF_obj

   Fahrzeug   PS  Preis  Reichweite
0      auto  150  35000         500
1      auto  200  35000         600
2  Motorrad  250  40000         550
3      auto  180  25000         700
4  Motorrad  160  22000         650
5      auto  220  32000         750
6  Motorrad  210  28000         800
7      auto  190  27000         720
8  Motorrad  230  32000         680
9      auto  170  25000         640

In [21]:
DF_obj.sort_values(by=['Preis', 'PS'], ascending=[False, False])

   Fahrzeug   PS  Preis  Reichweite
2  Motorrad  250  40000         550
1      auto  200  35000         600
0      auto  150  35000         500
8  Motorrad  230  32000         680
5      auto  220  32000         750
6  Motorrad  210  28000         800
7      auto  190  27000         720
3      auto  180  25000         700
9      auto  170  25000         640
4  Motorrad  160  22000         650

In [22]:
gr = DF_obj.groupby(['Fahrzeug'])
gr.mean()

             PS         Preis  Reichweite
Fahrzeug
Motorrad  212.5  30500.000000  670.000000
auto      185.0  29833.333333  651.666667

In [32]:
gr2 = gr[['PS', 'Preis', 'Reichweite']].mean()
gr2['Anzahl'] = gr.size()
gr2

             PS         Preis  Reichweite  Anzahl
Fahrzeug
Motorrad  212.5  30500.000000  670.000000       4
auto      185.0  29833.333333  651.666667       6