In [8]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

In [12]:
data ={'Fahrzeug': ['BMW', 'Audi', 'Mercedes', 'Toyota', 'Honda', 'Ford', 'Chevrolet', 'Nissan', 'Volkswagen', 'Hyundai'],
       'PS': [150, 200, 250, 180, 160, 220, 210, 190, 230, 170],
       'Preis': [35000, 35000, 40000, 25000, 22000, 32000, 28000, 27000, 32000, 25000],
       'Reichweite': [500, 600, 550, 700, 650, 750, 800, 720, 680, 640]}
DF_obj = pd.DataFrame(data)
DF_obj

     Fahrzeug   PS  Preis  Reichweite
0         BMW  150  35000         500
1        Audi  200  35000         600
2    Mercedes  250  40000         550
3      Toyota  180  25000         700
4       Honda  160  22000         650
5        Ford  220  32000         750
6   Chevrolet  210  28000         800
7      Nissan  190  27000         720
8  Volkswagen  230  32000         680
9     Hyundai  170  25000         640

In [14]:
DF_obj.sort_values(by=['Preis', 'PS'], ascending=[False, False])

     Fahrzeug   PS  Preis  Reichweite
2    Mercedes  250  40000         550
1        Audi  200  35000         600
0         BMW  150  35000         500
8  Volkswagen  230  32000         680
5        Ford  220  32000         750
6   Chevrolet  210  28000         800
7      Nissan  190  27000         720
3      Toyota  180  25000         700
9     Hyundai  170  25000         640
4       Honda  160  22000         650